name: Build OPPO A32 Kernel

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        default: 'kernel_only'
        type: choice
        options:
          - kernel_only   # 只编译内核
          - full_boot     # 编译内核并打包 boot 镜像

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu build-essential bc bison flex libssl-dev zip curl python3 device-tree-compiler libtinfo5
        sudo mkdir -p /lib/firmware

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        cp config/phone.config .config
        chmod +x build_kernel.sh
        ./build_kernel.sh

    - name: Pack Boot Image (Full Boot only)
      if: github.event.inputs.build_type == 'full_boot'
      run: |
        git clone https://github.com/BuildVoid/AIK-Linux-mirror.git aik
        cd aik
        cp ../factory_boot/boot.img ./
        ./unpackimg.sh boot.img
        cp ../out/arch/arm64/boot/Image.gz-dtb ./split_img/boot.img-kernel
        ./repackimg.sh
        mv image-new.img ../new-boot.img

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.build_type == 'full_boot' && 'new-boot-image' || 'kernel-image' }}
        path: |
          ${{ github.event.inputs.build_type == 'full_boot' && 'new-boot.img' || 'out/arch/arm64/boot/Image.gz-dtb' }}
